# .gitpod.yml
image: gitpod/workspace-python-3.11

tasks:
  - name: Install Dependencies
    init: |
      pip install --upgrade pip
      pip install -r requirements.txt || true # Instala dependencias si requirements.txt existe
    command: |
      echo "Environment ready. Run 'uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload'"

ports:
  - port: 8000
    onOpen: open-preview